### ISSUE TITLE
Request: MAM_ID file

### ISSUE THREAD

**Issue by derekoharrow** [johnpc/BookGrab#1]
Love this container - simple and effective.

One request - MAM_IDs expire and it's a bit of a pain having to update either a .env or docker compose file each time this happens.

I, and I presume many like me, have my MAM_ID stored in a text file that can be used by different containers.

Could you add an env variable that reads the MAM_ID from a text file? Then we wouldn't need to update the compose or env files.

ta!

**Comment by johnpc** [comment]
Added `MAM_TOKEN_FILE` support. You can now point it at a file containing your MAM cookie:

```yaml
environment:
  - MAM_TOKEN_FILE=/data/mam_token.txt
volumes:
  - ./mam_token.txt:/data/mam_token.txt:ro
```

Update the file whenever your token expires — no need to restart the container or edit compose. Falls back to `MAM_TOKEN` env var if the file isn't set.
